const tarotDeck = [
  { name: "Шут", id: "00", suit: "Major" },
  { name: "Маг", id: "01", suit: "Major" },
  { name: "Жрица", id: "02", suit: "Major" },
  { name: "Императрица", id: "03", suit: "Major" },
  { name: "Император", id: "04", suit: "Major" },
  { name: "Иерофант", id: "05", suit: "Major" },
  { name: "Влюбленные", id: "06", suit: "Major" },
  { name: "Колесница", id: "07", suit: "Major" },
  { name: "Сила", id: "08", suit: "Major" },
  { name: "Отшельник", id: "09", suit: "Major" },
  { name: "Колесо фортуны", id: "10", suit: "Major" },
  { name: "Справедливость", id: "11", suit: "Major" },
  { name: "Повешенный", id: "12", suit: "Major" },
  { name: "Смерть", id: "13", suit: "Major" },
  { name: "Умеренность", id: "14", suit: "Major" },
  { name: "Дьявол", id: "15", suit: "Major" },
  { name: "Башня", id: "16", suit: "Major" },
  { name: "Звезда", id: "17", suit: "Major" },
  { name: "Луна", id: "18", suit: "Major" },
  { name: "Солнце", id: "19", suit: "Major" },
  { name: "Суд", id: "20", suit: "Major" },
  { name: "Мир", id: "21", suit: "Major" },
  // Жезлы (Wands)
  { name: "Туз Жезлов", id: "22", suit: "Wands" },
  { name: "Двойка Жезлов", id: "23", suit: "Wands" },
  { name: "Тройка Жезлов", id: "24", suit: "Wands" },
  { name: "Четверка Жезлов", id: "25", suit: "Wands" },
  { name: "Пятерка Жезлов", id: "26", suit: "Wands" },
  { name: "Шестерка Жезлов", id: "27", suit: "Wands" },
  { name: "Семерка Жезлов", id: "28", suit: "Wands" },
  { name: "Восьмерка Жезлов", id: "29", suit: "Wands" },
  { name: "Девятка Жезлов", id: "30", suit: "Wands" },
  { name: "Десятка Жезлов", id: "31", suit: "Wands" },
  { name: "Паж Жезлов", id: "32", suit: "Wands" },
  { name: "Рыцарь Жезлов", id: "33", suit: "Wands" },
  { name: "Королева Жезлов", id: "34", suit: "Wands" },
  { name: "Король Жезлов", id: "35", suit: "Wands" },

  // Кубки (Cups)
  { name: "Туз Кубков", id: "36", suit: "Cups" },
  { name: "Двойка Кубков", id: "37", suit: "Cups" },
  { name: "Тройка Кубков", id: "38", suit: "Cups" },
  { name: "Четверка Кубков", id: "39", suit: "Cups" },
  { name: "Пятерка Кубков", id: "40", suit: "Cups" },
  { name: "Шестерка Кубков", id: "41", suit: "Cups" },
  { name: "Семерка Кубков", id: "42", suit: "Cups" },
  { name: "Восьмерка Кубков", id: "43", suit: "Cups" },
  { name: "Девятка Кубков", id: "44", suit: "Cups" },
  { name: "Десятка Кубков", id: "45", suit: "Cups" },
  { name: "Паж Кубков", id: "46", suit: "Cups" },
  { name: "Рыцарь Кубков", id: "47", suit: "Cups" },
  { name: "Королева Кубков", id: "48", suit: "Cups" },
  { name: "Король Кубков", id: "49", suit: "Cups" },

  // Мечи (Swords)
  { name: "Туз Мечей", id: "50", suit: "Swords" },
  { name: "Двойка Мечей", id: "51", suit: "Swords" },
  { name: "Тройка Мечей", id: "52", suit: "Swords" },
  { name: "Четверка Мечей", id: "53", suit: "Swords" },
  { name: "Пятерка Мечей", id: "54", suit: "Swords" },
  { name: "Шестерка Мечей", id: "55", suit: "Swords" },
  { name: "Семерка Мечей", id: "56", suit: "Swords" },
  { name: "Восьмерка Мечей", id: "57", suit: "Swords" },
  { name: "Девятка Мечей", id: "58", suit: "Swords" },
  { name: "Десятка Мечей", id: "59", suit: "Swords" },
  { name: "Паж Мечей", id: "60", suit: "Swords" },
  { name: "Рыцарь Мечей", id: "61", suit: "Swords" },
  { name: "Королева Мечей", id: "62", suit: "Swords" },
  { name: "Король Мечей", id: "63", suit: "Swords" },

  // Пентакли (Pentacles)
  { name: "Туз Пентаклей", id: "64", suit: "Pentacles" },
  { name: "Двойка Пентаклей", id: "65", suit: "Pentacles" },
  { name: "Тройка Пентаклей", id: "66", suit: "Pentacles" },
  { name: "Четверка Пентаклей", id: "67", suit: "Pentacles" },
  { name: "Пятерка Пентаклей", id: "68", suit: "Pentacles" },
  { name: "Шестерка Пентаклей", id: "69", suit: "Pentacles" },
  { name: "Семерка Пентаклей", id: "70", suit: "Pentacles" },
  { name: "Восьмерка Пентаклей", id: "71", suit: "Pentacles" },
  { name: "Девятка Пентаклей", id: "72", suit: "Pentacles" },
  { name: "Десятка Пентаклей", id: "73", suit: "Pentacles" },
  { name: "Паж Пентаклей", id: "74", suit: "Pentacles" },
  { name: "Рыцарь Пентаклей", id: "75", suit: "Pentacles" },
  { name: "Королева Пентаклей", id: "76", suit: "Pentacles" },
  { name: "Король Пентаклей", id: "77", suit: "Pentacles" },




];

module.exports = { tarotDeck };